### DISCUSSION TITLE
Stackoverflow activity doesn't show activity

### DISCUSSION THREAD

**Discussion by nardiyansah** [gautamkrishnar/blog-post-workflow#106] [Q&A] [answered]
Hello @gautamkrishnar , I recently use your GitHub action and in the section for StackOverflow it just gives a link to the page, didn't show activity like `comment` or `answer`. Are this is happening because I am new in StackOverflow? I just ask 1 question and add 1 comment in StackOverflow.

![Screenshot from 2021-11-08 19-07-21](https://user-images.githubusercontent.com/41910581/140739996-4353f99b-0744-4da1-b48b-b421e4bb68ff.png)

**Comment by gautamkrishnar** [comment, marked as answer]
@nardiyansah have you tried using the following config:
```yml
name: Latest stack overflow activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '0 1 * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://stackoverflow.com/feeds/user/15678198,https://askubuntu.com/feeds/user/1522489"
          filter_comments: ""
```
