### DISCUSSION TITLE
Getting Hashnode Blog post Image from the feed

### DISCUSSION THREAD

**Discussion by sansk** [gautamkrishnar/blog-post-workflow#116] [Q&A] [answered]
**Is your feature request related to a problem? Please describe.**
I would like to have Image/Thumbnails displayed along with my blog post title, Date & Description

**Describe the solution you'd like**
Able to fetch the image from the hashnode feed and use it in the `template` option.

**Describe alternatives you've considered**
Can have a workaround with `custom_tags` just like something you have suggested for `$videoId`.

**Comment by gautamkrishnar** [comment, marked as answer]
@sansk please try using the yaml below:
```
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://theintrovertcoder.hashnode.dev/rss.xml"
          max_post_count: 3
          custom_tags: "postImage/cover_image/"
          template: "$postImage"
          commit_message: "Updated README with the latest blog posts"
```


You can now use `$postImage` in the template to display the image. Date and the rest can be rendered using corresponding variables. Please check https://github.com/gautamkrishnar/blog-post-workflow#options template row for the list of variables available.

**Reply by Sagar0-0** [reply]
What could be the custom tag for getting medium post banner? And how did you actually find that this specific custom tag will work for hashnode?

**Comment by sansk** [comment]
Thanks @gautamkrishnar.
I have added images to the latest blog post items

![image](https://user-images.githubusercontent.com/3327904/152119232-9020298a-dc3c-4917-a922-8d2f14b5e312.png)
https://github.com/sansk/sansk#my-latest-blog-posts-

My `blog-post-workflow.yml`,
```
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://theintrovertcoder.hashnode.dev/rss.xml"
          max_post_count: 3
          commit_message: "Updated README with the latest blog posts"
          date_format: "mmm d, yyyy"
          custom_tags: "postImage/cover_image/"
          template: '<table style="width:100%"><tr><td style="width:150px"><a href="$url"><img width="140px" src="$postImage"></a></td><td><a href="$url">$title</a> | $date </td></tr></table>$newline'
```

**Reply by gautamkrishnar** [reply]
@sansk `post.description.replace(/<\/?[^>]+(>|$)/g, "")` will replace HTML. .slice will slice the replaced string. 

Example:
![Screenshot 2022-02-02 at 2 14 56 PM](https://user-images.githubusercontent.com/8397274/152121057-f3f308d1-4425-44c6-9eb9-c496c4a2509e.png)

**Reply by sansk** [reply]
Yeah, it is working in the console. but when I added in the workflow, it doesn't strip the HTML.
![image](https://user-images.githubusercontent.com/3327904/152121987-49c9d6f3-1ae2-461e-a103-1d02d8257e8b.png)

The workflow for the above,
```
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://theintrovertcoder.hashnode.dev/rss.xml"
          max_post_count: 3
          commit_message: "Updated README with the latest blog posts"
          date_format: "mmm d, yyyy"
          custom_tags: "postImage/cover_image/"
          item_exec: |
            post.description = post.description.replace(/<\/?[^>]+(>|$)/g, "").slice(0,100)
          template: '<table style="width:100%"><tr><td style="width:150px"><a href="$url"><img width="140px" src="$postImage"></a></td><td><a href="$url">$title</a> | $date <br> $description...</td></tr></table>$newline'
```

**Reply by gautamkrishnar** [reply]
Maybe it is github messing up the regular expression. Will take a look later. Thanks for letting me know

**Reply by sansk** [reply]
Sure. Thanks @gautamkrishnar 
Your speed of replying amazes me 🙂

**Reply by gautamkrishnar** [reply]
@sansk this is due to the html encoding.  Please use the following:
```yaml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://theintrovertcoder.hashnode.dev/rss.xml"
          max_post_count: 3
          commit_message: "Updated README with the latest blog posts"
          date_format: "mmm d, yyyy"
          custom_tags: "postImage/cover_image/"
          disable_html_encoding: true
          item_exec: |
            post.description = post.description.replace(/<\/?[^>]+(>|$)/g, "").slice(0,100)
          template: '<table style="width:100%"><tr><td style="width:150px"><a href="$url"><img width="140px" src="$postImage"></a></td><td><a href="$url">$title</a> | $date <br> $description...</td></tr></table>$newline'
```
