### DISCUSSION TITLE
Question: How to make this work with protected branch

### DISCUSSION THREAD

**Discussion by xiaomi7732** [gautamkrishnar/blog-post-workflow#127] [Q&A]
Error log when the target branch is protected, what is the way to set it up to make it work?

```log
Run gautamkrishnar/blog-post-workflow@master
https://www.youtube.com/feeds/videos.xml?channel_id=UCFVGdkhRh174GKg9gVEhY6A runner succeeded. Post count: 15
Writing to ./README.md
[main 6b702c0] Updated with the latest blog posts
 1 file changed, 5 insertions(+)
remote: error: GH006: Protected branch update failed for refs/heads/main.        # the main branch is protected
remote: error: At least 1 approving review is required by reviewers with write access.        
To [redated]
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/redacted.git'
Error: {"code":1,"outputData":""}
```

**Comment by gautamkrishnar** [comment]
@xiaomi7732 Nope. it wont work. Protected branches cannot be pushed directly, It is a github feature. You should open a PR to update it. Just disable branch protection if you want to use the action and to do the automated updates.

**Reply by xiaomi7732** [reply]
Okay, then, 2nd to the best, is it possible to use the action to generate a PR?

**Reply by gautamkrishnar** [reply]
Nope you should use some other github action for that one. I would recommend you to just turn off the branch protection rules. Generating PRs porgamaticially can be a tedious task if you have lots of blog post publishing happening on your repo.

**Reply by gautamkrishnar** [reply]
You can read more here: https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101

**Comment by gautamkrishnar** [comment]
@xiaomi7732 if you are an admin in the repository in the question you can proably try passing the PAT token to the github action using gh_token key. Create one from here:  https://github.com/settings/tokens and add it to your own repositorie's secrets as `PAT_GITHUB`. This wont work if you have branch protection enabled for admins as well.

```
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
          gh_token: ${{ secrets.PAT_GITHUB }}
```
