### DISCUSSION TITLE
Numbered list between the START and END tags

### DISCUSSION THREAD

**Discussion by LDdvlp** [gautamkrishnar/blog-post-workflow#138] [Q&A]
Bonjour Gautam,

Could you please create an option to have a numbered list intead of a bulleted list between `<!-- BLOG-POST-LIST:START -->` and `<!-- BLOG-POST-LIST:END -->` ?

Example :

**This list :**

1. REST API Design Best Practices – How to Build a REST API with JavaScript, Node.js, and Express.js
2. Traits of a senior software engineer
3. State of CSS 2022
4. 16 useful TypeScript and JavaScript shorthands to know
5. Object-Oriented Programming in JavaScript for Beginners

**instead of :**

- REST API Design Best Practices – How to Build a REST API with JavaScript, Node.js, and Express.js
- Traits of a senior software engineer
- State of CSS 2022
- 16 useful TypeScript and JavaScript shorthands to know
- Object-Oriented Programming in JavaScript for Beginners

The option might be `numbered_list: false` by default.

Or maybe does it exist a tip to do this ?

Thank you,
Loïc.

**Comment by gautamkrishnar** [comment]
@LDdvlp this is already supported you can acheive this by doing:
```yaml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar/"
          template: "$counter. [$title]($url)"
          tag_post_pre_newline: true
```

**Reply by LDdvlp** [reply]
Bonjour Gautam,

Thanks for your answer.

Your solution works, but there is no new lines between the items of the list, so I poked around in your code, and i have found this description in your action.yml file :

```
  tag_post_pre_newline:
    description: "Inserts newline before the closing tag and after the opening tag when using the template option, for formatting"
    required: false
  template:
    description: "Template to use while creating the list of posts. It can contain $title,$url, $newline and $date as variables"
    default: "default"
    required: false
```
For `template`, `$newline` is interesting, then here is my solution :

```
name: daily.dev Bookmarks
on:
  schedule:
    # Runs 2 Minutes To Midnight (and Not to the Hills) [Up the Irons !]
    - cron: '58 23 * * *'
  workflow_dispatch:

jobs:
  daily-dev-bookmarks:
    name: Update this repo's README with latest bookmarks from daily.dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in daily.dev bookmarks 
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "daily.dev BOOKMARKS"
          max_post_count: 15
          commit_message: "Updated README.md with the 15 latest Daily Dev bookmarks"
          feed_list: "https://api.daily.dev/rss/b/11c29ef8-70f1-4c29-b88c-4a00bb6cefd0"
          tag_post_pre_newline: true
          template: "$counter. [$title]($url)$newline"
```
And yes, it is important to have `tag_post_pre_newline: true`, else (false by default), the first item of the list is posted in Markdown syntax.

Bonne journée,
Loïc.
