### DISCUSSION TITLE
Use main instead of master branch

### DISCUSSION THREAD

**Discussion by annegentle** [gautamkrishnar/blog-post-workflow#145] [General]
**Is your feature request related to a problem? Please describe.**
Hi, I'm looking for ways to eliminate `master` from our org's scripts, and it would be great to be able to refer to a branch named `main` for this action.
**Describe the solution you'd like**
Provide a branch named `main` for this action.

**Describe alternatives you've considered**
I could point to one of the other named branches or a release tag.

**Comment by gautamkrishnar** [comment]
@annegentle i am not planning to use main in the project for now. Feel free to use a published version instead of using master. Eg: for the latest version:

```yaml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@1.7.2
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
```

You can use any versions that are available in: https://github.com/gautamkrishnar/blog-post-workflow/releases
