### DISCUSSION TITLE
Conditional statement for blogs / remove duplicates

### DISCUSSION THREAD

**Discussion by avipars** [gautamkrishnar/blog-post-workflow#158] [General]
Occasionally, I guest post or re-share the article on two separate sources, is there a way to either have some conditional statement inside your action or a setting to ignore duplicate posts based on title?

**Comment by gautamkrishnar** [comment]
@avipars just do it via `item_exec`. You can execute javascript code before each item is getting set. 

Update: Adding a feature like that would be better. I will work on it when I have time.

**Reply by gautamkrishnar** [reply]
@avipars you can now do the following:
```yaml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yadaa
        uses: gautamkrishnar/blog-post-workflow@master
        with: #parsing rss feeds
          max_post_count: "6"
          user_agent: "gh-actions-profile"
          remove_duplicates: true
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYzocrbgFApPAGhq7PAw9Gw,https://aviparshan.medium.com/feed,https://sales.aviparshan.com/feeds/posts/default?alt=rss,https://tech.aviparshan.com/feeds/posts/default?alt=rss,https://www.youtube.com/feeds/videos.xml?channel_id=UCxSsckr_q-SfZ7lkoh2dVCQ"
```
It is released on https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.7.6
