### DISCUSSION TITLE
The blog workflow fails to auto run as schedule every time the feed link gets updated

### DISCUSSION THREAD

**Discussion by Sacsam005** [gautamkrishnar/blog-post-workflow#165] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/88958992/186722178-817a0159-b03d-4d22-80d9-feaf7a9aa8db.png)

```
name: Latest blog post workflow
on:
  schedule: 
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://opensource.com/feed"
```
