### DISCUSSION TITLE
Does this workflow support user's GitHub Feed?

### DISCUSSION THREAD

**Discussion by clcmo** [gautamkrishnar/blog-post-workflow#190] [Q&A] [answered]
**Is your feature request related to a problem? Please describe.**
Not a problem, but I think If the workflow supports the user activities on GitHub. So, It's a suggestion of feature.

**Describe the solution you'd like**
Show the latest activities from the user on README.

**Comment by gautamkrishnar** [comment, marked as answer]
Github has an RSS feed that you can use. in your case you can try using:

```yaml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://github.com/clcmo.atom"
```

Please follow the steps noted here: https://github.com/gautamkrishnar/blog-post-workflow#how-to-use
