### DISCUSSION TITLE
[Bug]: Fails when there is no <title> in <item>

### DISCUSSION THREAD

**Discussion by nie7321** [gautamkrishnar/blog-post-workflow#206] [Q&A]
**Describe the bug**
When there is no `<title>` in an RSS feed's `<item>`, [the action fails](https://github.com/nie7321/nie7321/actions/runs/4667710149/jobs/8263849935#step:3:30):

```
            title: item.title.trim(),
                              ^

TypeError: Cannot read properties of undefined (reading 'trim')
```

**Expected behavior**
The RSS file in question is from a microblogging site. It's a valid RSS 2.0 file. Per the [RSS 2.0 specification](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt):

>  All elements of an item are optional, however at least one of title or description must be present.

In this feed, `<title>` is absent, but `<description>` is available:

```xml
    <item>
      <guid isPermaLink="true">https://mastodon.yshi.org/@owls/110177333762426246</guid>
      <link>https://mastodon.yshi.org/@owls/110177333762426246</link>
      <pubDate>Tue, 11 Apr 2023 00:24:55 +0000</pubDate>
      <description>&lt;p&gt;!deer&lt;/p&gt;</description>
    </item>
```

If you would like to see the whole feed, it is available at `https://mastodon.yshi.org/@owls.rss`.

**Screenshots**

**Workflow Yml Used**
```yml
name: Dynamic README
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_names: "owlblog,microblog"
          feed_list: "https://godless-internets.org/feed/,http://mastodon.yshi.org/@owls.rss"
```

**Comment by gautamkrishnar** [comment]
@nie7321 title check can be disabled by setting `disable_item_validation` also you can skip items that don't have a title via `item_exec` read more about that in the options list: https://github.com/gautamkrishnar/blog-post-workflow#options

You can use a combination of templates combined with the above options to make the workflow work.
ex: https://github.com/gautamkrishnar/blog-post-workflow/issues/142 and https://github.com/gautamkrishnar/blog-post-workflow/issues/34#issuecomment-706582788

**Reply by nie7321** [reply]
@gautamkrishnar Disabling validation does not prevent the `item.title.trim()` error, and the trim attempt fails before the `item_exec` code is run. 

I don't see a combination of settings that will allow this to work if the feed items do not have a title. I think [this line](https://github.com/gautamkrishnar/blog-post-workflow/blob/master/src/blog-post-workflow.js#L159) should only be run if validation is enabled (or it should be null-safe, e.g. `item.title?.trim()`).

**Reply by gautamkrishnar** [reply]
@nie7321 you can ignore item without a title by using the item_exec key. Simply use `post = null` as the value to ignore the posts without a title.

**Reply by gautamkrishnar** [reply]
In your case the code will be:
```yaml
name: Dynamic README
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_names: "owlblog,microblog"
          feed_list: "https://godless-internets.org/feed/,http://mastodon.yshi.org/@owls.rss"
          disable_item_validation: "true"
          item_exec: "if (!post.title) post = null"
```
Please let me know if this works.

**Reply by lostfocus** [reply]
Is there a way to use the `<description>` if the title isn't set?

**Reply by gautamkrishnar** [reply]
@lostfocus 
try:
```
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar"
          disable_item_validation: "true"
          item_exec: "if (!post.title) post.title = post.description"
```
