### DISCUSSION TITLE
Not working with personal blog website

### DISCUSSION THREAD

**Discussion by sajadshafi** [gautamkrishnar/blog-post-workflow#212] [Q&A]
I have a website hosted where I upload articles, but the workflow is not fetching my posts. I am getting the error:

`Error: Feed not recognized as RSS 1 or 2`

[My blog](https://www.birdscode.com).

My Readme file contains the comments:

```md
# Blog posts
<!-- BLOG-POST-LIST:START -->
<!-- BLOG-POST-LIST:END -->
```
YML file:
```yml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.birdscode.com"
```

How to fix this issue.
