### DISCUSSION TITLE
Error: Request timed out after 60000ms

### DISCUSSION THREAD

**Discussion by AyaneAI** [gautamkrishnar/blog-post-workflow#220] [Q&A] [answered]
I have a CSDN blog and want to subscribe my blog
RSS url: https://blog.csdn.net/qq_34102672/rss/list

My Readme file contains the comments:
```
### Latest Blog Posts
<!-- BLOG-POST-LIST:START -->
<!-- BLOG-POST-LIST:END -->
```
YML file:
```
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.csdn.net/qq_34102672/rss/list"
```

![image](https://github.com/gautamkrishnar/blog-post-workflow/assets/48854072/bc9f1b70-c7b1-4670-940f-584a435e0e20)

But it doesn't seem to work.

It's appreciated if you could tell me how to fix this issue.
