### DISCUSSION TITLE
Error: unable to verify the first certificate

### DISCUSSION THREAD

**Discussion by chatseeon** [gautamkrishnar/blog-post-workflow#222] [Q&A] [answered]
I've encountered a error and I'm not sure how to resolve it.
![chrome_screenshot_github com (2)](https://github.com/gautamkrishnar/blog-post-workflow/assets/107085673/55aaad1a-7b2d-489a-b1f7-86d0cfe4705a)
![chrome_screenshot_github com (1)](https://github.com/gautamkrishnar/blog-post-workflow/assets/107085673/79c0dda3-e85f-43fa-b437-eb1b7ef566e5)
![chrome_screenshot_github com](https://github.com/gautamkrishnar/blog-post-workflow/assets/107085673/a81ec4ca-d259-4a53-8769-005b679b643a)

**Comment by gautamkrishnar** [comment, marked as answer]
@chatseeon this is because of a SSL issue on your website. Workflow can't do anything to fix it. You should fix it in your website's source code.
```bash
> curl https://csworldlet.top/author/chatseeon/feed/
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

Alternatively you can ignore the SSL errors via:
```yaml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        env:
           NODE_TLS_REJECT_UNAUTHORIZED: 0
        with:
          feed_list: "https://csworldlet.top/author/chatseeon/feed/"
```
