### DISCUSSION TITLE
Rss Feed Filter by author

### DISCUSSION THREAD

**Discussion by manishtiwari25** [gautamkrishnar/blog-post-workflow#247] [Q&A] [answered]
Hey,
I have a blog post where multiple people post, is there a way to filter the post by author?

for each post in feed.xml we have a author entry.
<img width="1144" alt="image" src="https://github.com/gautamkrishnar/blog-post-workflow/assets/50008945/9ca3fd6b-da99-4378-8bf6-27088c8da80c">

if it is already there could you please point me towards documentations? or if now I am happy to contribute.

I have already looked into the code and documentation and didn't find anything related to this.
Thanks :)

**Comment by gautamkrishnar** [comment, marked as answer]
just use `item_exec`. You will be able to filter it. in this case:

```yaml
name: Latest Contributions
on:
  schedule:
    # Runs every hour
    - cron: "0 2 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-stackexchange:
    name: Update this repo's README with latest contributions
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "Blog"
          feed_list: "https://blogs.bitesinbyte.com/feed.xml"
          max_post_count: 3
          item_exec: |
                     if (item.author !== "manishtiwari25") post = null;
```

Read more: https://github.com/gautamkrishnar/blog-post-workflow/issues/34#issuecomment-706582788

You can also put console.log(item) to see what exactly your feed returns and adjust the logic accordingly.
