### DISCUSSION TITLE
HTML display

### DISCUSSION THREAD

**Discussion by kangyans** [gautamkrishnar/blog-post-workflow#255] [Q&A] [answered]
### Describe the bug
The display of $B_1^+$ appears to ```B<sub>1</sub><sup>+</sup>```

### Expected behavior
display the correct format, in my example,: $B_1^+$

### Workflow Yml Used
```
 - uses: actions/checkout@v2
 - uses: gautamkrishnar/blog-post-workflow@v1
```

### Double check the following
Before opening a bug, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [x] I had gone through the [FAQs](https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues) 
- [x] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)

**Comment by gautamkrishnar** [comment, marked as answer]
@kangyans please use `disable_html_encoding: true` 

```yml
# This is a basic workflow to help you get started with Actions

name: Latest blog post workflow

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updata-readme-with-blog:
    name: Updata this repo's README with the latest blog posts
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v2
          - uses: gautamkrishnar/blog-post-workflow@v1
            with:
              feed_list: "https://pubmed.ncbi.nlm.nih.gov/rss/search/16eWR_JeA5gcz8mL6exRVyljdv1Bg_b5daAnspofyJehJ6_wD-/?limit=15&utm_campaign=pubmed-2&fc=20240423194405"
              max_post_count: 10
              disable_html_encoding: true
```
