### DISCUSSION TITLE
How to create a template that outputs a table?

### DISCUSSION THREAD

**Discussion by omariosouto** [gautamkrishnar/blog-post-workflow#64] [Q&A] [answered]
Is possible to output a table?

**Comment by gautamkrishnar** [comment, marked as answer]
Thanks for asking @omariosouto, yes it is possible via `template` key. Example:

Readme.md:
```md
<table>
    <tr><th>Title</th><th>Link</th></tr>
    <!-- STACKOVERFLOW:START -->
    <!-- STACKOVERFLOW:END -->
</table>
```

workflows/stack-oveflow-workflow.yml
```yml
name: Latest stack oveflow activity
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://stackoverflow.com/feeds/user/4214976"
          template: "<tr><td>$title</td><td>$url</td></tr>"
```

Preview: https://github.com/gkr-bot/gkr-bot#latest-stackoveflow-activity-of-gautamkrishnar
