### ISSUE TITLE
Error: Error: Attribute without value Line: 0 Column: 2560 Char: >[Bug]: 

### ISSUE THREAD

**Issue by levalencia** [gautamkrishnar/blog-post-workflow#100]
**Describe the bug**
When it runs I get this error:
```
Run gautamkrishnar/blog-post-workflow@master
  with:
    feed_list: https://feedly.com/i/subscription/feed%2Fhttp%3A%2F%2Fluisevalencia.com%2Frss%2Fn
    gh_token: ***
    readme_path: ./README.md
    max_post_count: 5
    disable_sort: false
    filter_comments: medium,stackoverflow/Comment by $author/,stackexchange/Comment by $author/
    template: default
    date_format: UTC:ddd mmm dd yyyy h:MM TT
    user_agent: rss-parser
    accept_header: application/rss+xml
    commit_message: Updated with the latest blog posts
    committer_username: blog-post-bot
    committer_email: blog-post-bot@example.com
    output_only: false
    enable_keepalive: true
    retry_count: 0
    retry_wait_time: 1
Error: https://feedly.com/i/subscription/feed%2Fhttp%3A%2F%2Fluisevalencia.com%2Frss%2Fn runner failed, please verify the configuration. Error:
Error: Error: Attribute without value
Line: 0
Column: 2560
Char: >
0 blog posts fetched
```

**Expected behavior**
fetch blog posts

**Screenshots**

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://luisevalencia.com/rss/"
```

**Additional context**
