### ISSUE TITLE
[Bug]: Hugo links seem to not work?

### ISSUE THREAD

**Issue by yqlbu** [gautamkrishnar/blog-post-workflow#103]
**Describe the bug**

Looks like it is incompatible with Hugo Site

**Screenshots**

![](https://ibb.co/P4nXKnK)

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually with a trigger
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # you can change this to your own RSS feed
          feed_list: "https://www.hikariai.net/index.xml"
```

**Additional context**
