### ISSUE TITLE
[Feature]: Tag collection

### ISSUE THREAD

**Issue by LucasTMP** [gautamkrishnar/blog-post-workflow#105]
![image](https://user-images.githubusercontent.com/50775822/140431885-bc464acc-65ae-4b7a-8f01-b5cef39ac0d2.png)

Is there any way to get each tag in this "collection"?
(Dev.To) https://dev.to/feed/lucastmp

It would be really nice to have all the tags of the posts, so it would be possible to search more easily.

**Comment by gautamkrishnar** [comment]
@LucasTMP Please use `template` parameter and `categories` variable for this purpose.
Eg:

```yml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/lucastmp"
          template: $newline - [$title]($url) - $categories
```
