### ISSUE TITLE
Truncated output from Github Action

### ISSUE THREAD

**Issue by lyqht** [gautamkrishnar/blog-post-workflow#110]
**Describe the bug**
Using the action with the following .yml of `output_only=true`

The output I got is truncated. An example can be seen from [this workflow run](https://github.com/lyqht/test-repo-github-action-workflow/runs/4367439394?check_suite_focus=true) under the `Run cd /home/runner/work/_actions/lyqht/article-count-workflow/main && npm install && node articleCount.js` command

**Expected behavior**
I don't actually require the full array of content, for my purposes, I just wanted to get the array count of the all the articles from the feeds.

**Workflow Yml Used**

```yml
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Running Gautam's Blog post workflow 
    uses: gautamkrishnar/blog-post-workflow@master
    id: blogpost_workflow
    with:
      comment_tag_name: ${{inputs.comment_tag_name}}
      commit_message: "Updated Badge with latest number of articles"
      feed_list: ${{inputs.feed_list}}
      max_post_count: 1000000
      output_only: true
```

**Comment by gautamkrishnar** [comment]
The output is usually truncated due to Github's environment limits. The error message might show up as "Error: Argument list too long" if we try to echo the generated output. Added a fix that redirects the generated JSON into a file (`/tmp/blog_post_workflow_output.json`) so that the users can consume the generated contents without using the github action's native echo commands.
You can now do something like:
```yml
  - name: Running Gautam's Blog post workflow 
    uses: gautamkrishnar/blog-post-workflow@master
    id: blogpost_workflow
    with:
      comment_tag_name: ${{inputs.comment_tag_name}}
      commit_message: "Updated Badge with latest number of articles"
      feed_list: ${{inputs.feed_list}}
      max_post_count: 1000000
      output_only: true
 - name: Echo the length
    run: echo $(jq '. | length' /tmp/blog_post_workflow_output.json)
```
