### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Sacsam005** [gautamkrishnar/blog-post-workflow#111]
**Expected behavior**
The error says repository not found which I don't find valid, if not please enlighten me.

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
  schedule: 
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: Sacsam005/blog-post-workflow@master
        with:

          feed_list: "https://shachinmagar120sm.wixsite.com/codingproficiency/blog-feed.xml"
```

**Additional context**
I tried every possible way of doing that, checked my RSS feed link, but failed.

**Comment by gautamkrishnar** [comment]
@Sacsam005 you are using it wrong. Please read the instructions on the readme before using the workflow.

Watch this video for a demo on how to use the workflow: https://www.youtube.com/watch?v=ECuqb5Tv9qI&t=272s

**Comment by gautamkrishnar** [comment]
Use the following code in your workflow:
```yaml
name: Latest blog post workflow
on:
  schedule: 
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://shachinmagar120sm.wixsite.com/codingproficiency/blog-feed.xml"
````
