### ISSUE TITLE
[Feature]: Add option for html and js files

### ISSUE THREAD

**Issue by KunalSingh19** [gautamkrishnar/blog-post-workflow#112]
pls add option of selecting path of file/ file extension

**Comment by gautamkrishnar** [comment]
@KunalSingh19 can you please explain what are you trying to achieve?

**Comment by gautamkrishnar** [comment]
@KunalSingh19 you can select path of the readme file using the `readme_path` option.
```yaml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar"
          readme_path: "./example.md"
```
