### ISSUE TITLE
[Bug]: WordPress feed

### ISSUE THREAD

**Issue by Artlfmj** [gautamkrishnar/blog-post-workflow#114]
**Describe the bug**

During the run I get a 503 error

**Expected behavior**

Run and fetch the endpoint

**Screenshots**

**Workflow Yml Used**
```yml
name: Latest stack overflow activity
on:
  schedule:
    # Runs every 2 minutes
    - cron: '*/2* * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://actu-dados.com/feed/"
```

**Additional context**
