### ISSUE TITLE
[Bug]: Workflow run failed (red x) 

### ISSUE THREAD

**Issue by codewizard13** [gautamkrishnar/blog-post-workflow#118]
**Describe the bug**
The Latest blog post workflow keeps failing EVERY TIME to grab my feed from [https://erichepperle.com/blog/feed/](https://erichepperle.com/blog/feed/) and thus, never populates the README.md file.

**Expected behavior**
- The action checkmark should turn green upon manual clicking of "Run workflow" button
- BLOG-POST-LIST comments in README.md should auto-populate with my latest 5 blog posts

**Things I Tried**
- Replaced my feed URL with feed set from the example --> this was **_the only time_** that the action worked (see the green checkmark  in screenshot).
```yml
feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
```

**Screenshots**
**100% failure**: The only time the action worked was with the default feed set from [gautamkrishnar's example](https://github.com/gautamkrishnar/blog-post-workflow#how-to-use).
![Action failure log](https://user-images.githubusercontent.com/3443044/153719961-f40cb177-ea92-4eb1-88d4-b1600376bbc8.png)

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://erichepperle.com/blogfeed/"
```

**Additional context**
You can see that the feed url is a working WordPress blog feed:
```xml
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>Eric L. Hepperle&#8217;s Blog on Life &#038; Technology &#8211; EricHepperle.com</title>
	<atom:link href="https://erichepperle.com/blog/feed/" rel="self" type="application/rss+xml" />
	<link>https://erichepperle.com</link>
	<description>A Creative Professional Hungrily Pursues the Kingdom of God and His Righteousness</description>
	<lastBuildDate>Tue, 01 Feb 2022 16:17:12 +0000</lastBuildDate>
	<language>en-US</language>
	<sy:updatePeriod>
	hourly	</sy:updatePeriod>
	<sy:updateFrequency>
	1	</sy:updateFrequency>
	<generator>https://wordpress.org/?v=5.8.3</generator>

<image>
	<url>https://erichepperle.com/wp-content/uploads/2021/11/ehd_logo_20211109_EHW_Favicon_LogoMakr_02-150x150.png</url>
	<title>Eric L. Hepperle&#8217;s Blog on Life &#038; Technology &#8211; EricHepperle.com</title>
	<link>https://erichepperle.com</link>
	<width>32</width>
	<height>32</height>
</image> 
	<item>
		<title>Learning Evolus Pencil by Modeling a Mockup Wireframe of WordPress Dashboard</title>
		<link>https://erichepperle.com/learning-evolus-pencil-by-modeling-a-mockup-wireframe-of-wordpress-dashboard/</link>
					<comments>https://erichepperle.com/learning-evolus-pencil-by-modeling-a-mockup-wireframe-of-wordpress-dashboard/#respond</comments>
		
		<dc:creator><![CDATA[Eric Hepperle]]></dc:creator>
		<pubDate>Thu, 04 Nov 2021 12:31:41 +0000</pubDate>
				<category><![CDATA[All]]></category>
		<category><![CDATA[Design]]></category>
		<category><![CDATA[Eric's Graphic Designs]]></category>
		<category><![CDATA[Graphic Design]]></category>
		<category><![CDATA[Journal Notes]]></category>
		<category><![CDATA[Eric's Designs]]></category>
		<category><![CDATA[Eric's Journal]]></category>
		<category><![CDATA[Evolus Pencil]]></category>
		<category><![CDATA[Mockup]]></category>
		<category><![CDATA[open source]]></category>
		<category><![CDATA[Web Design]]></category>
		<category><![CDATA[Wireframing]]></category>
		<category><![CDATA[WordPress]]></category>
		<guid isPermaLink="false">https://erichepperle.com/?p=13580</guid>
... etc.
```
