### ISSUE TITLE
[Feature]: From Date

### ISSUE THREAD

**Issue by courtneyr-dev** [gautamkrishnar/blog-post-workflow#123]
**Is your feature request related to a problem? Please describe.**
I want to specify all posts with a timerange, such as the last 7 days or by calendar month. 

**Describe the solution you'd like**
Add an option for date parameters

**Describe alternatives you've considered**
I manually check the dates

**Additional context**
Creating a public repo for https://learn.wordpress.org to show 4 content types that have been published that week/month.

**Comment by gautamkrishnar** [comment]
@courtneyr-dev thanks a lot for the suggestion. This will be a cool feature to have. Currently, you can do the following workaround to get this working.

To filter out posts from last 7 days
```yaml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.gautamkrishnar.com/feed/"
          item_exec: |
                 const DAY = 24 * 60 * 60 * 1000;
                 const DAYS_AGO = 7;  // 7 days ago
                 const dateObj = new Date(Date.now() - DAYS_AGO);
                 if ( post.date >=  dateObj) post = null;
```
