### ISSUE TITLE
[Bug]: Unable to git pull

### ISSUE THREAD

**Issue by curtiscde** [gautamkrishnar/blog-post-workflow#128]
Hey 👋  thanks for this workflow! I'm having an issue I would appreciate some help with.

**Describe the bug**
I receive the following error when the workflow runs:

```
Error: {"code":1,"outputData":""}
```

I've forked the repo and added some logs to debug this, and it seems as if I might be having an issue with the `git pull` step:

```js
core.info('git pull')
if (!process.env.TEST_MODE) {
  await exec('git', ['config', 'pull.rebase', 'true'], { stdio: ['pipe', 'pipe', 'pipe'] });
  // Pulling the latest changes from upstream
  await exec('git', ['pull'], { stdio: ['pipe', 'pipe', 'pipe'] });
}
core.info('git pull complete')
```

And the logs I receive are:

```
Run curtiscde/blog-post-workflow@f
https://curtiscode.dev/index.xml runner succeeded. Post count: 20
add feed name to the items
slice the max count
git pull
Error: {"code":1,"outputData":""}
```
https://github.com/curtiscde/curtiscde/runs/5673355105?check_suite_focus=true

**Expected behavior**
The git pull stage should succeed, and continue to the next steps

**Workflow Yml Used**
```yml
jobs:
  update-readme-with-blog-posts:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in curtiscode.dev posts
        uses: curtiscde/blog-post-workflow@f
        with:
          feed_list: "https://curtiscode.dev/index.xml"
```
https://github.com/curtiscde/curtiscde/blob/posts/.github/workflows/blog-post-workflow.yml

**Comment by gautamkrishnar** [comment]
@curtiscde please use the workflow as exactly mentioned in the [README.md](https://github.com/gautamkrishnar/blog-post-workflow#how-to-use) file. **Do not** use it via on push trigger.
Sane code is working fine for me on the repo: https://github.com/gkr-bot/test-001

Just use the following yaml file after adding the comment in your readme:
```
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://curtiscode.dev/index.xml"
```
