### ISSUE TITLE
[Bug]: Hashnode RSS Feed doesn't appear on GitHub Profile

### ISSUE THREAD

**Issue by polilluminato** [gautamkrishnar/blog-post-workflow#13]
I tried to use this workflow, in particular the standard `blog-post-workflow.yml`, to add to my GitHub profile my RSS feed on [Hashnode](https://hashnode.com/).

**Steps to reproduce the behavior**

1. Use the standard `blog-post-workflow.yml` as described in the `readme` file
2. Add to the `feed_list` option my RSS feed on Hasnode: [https://polilluminato.hashnode.dev/rss.xml](https://polilluminato.hashnode.dev/rss.xml)
3. Add the `workflow_dispatch`: option in the _on_ section of the `blog-post-workflow.yml` as described in this [video](https://www.youtube.com/watch?v=ECuqb5Tv9qI) on YouTube by [codeSTACKr](https://github.com/codeSTACKr)
4. Add the tag on my profile page
```
<!-- BLOG-POST-LIST:START -->
<!-- BLOG-POST-LIST:END -->
```
5. Run manually the workflow on GitHub actions
6. Nothing appears on my GitHub profile

**My `blog-post-workflow.yml`**

```
name: Lastest Hashnode Blog Post
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Hashnode blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "HASHNODE"
          commit_message: "Updated readme with the latest Hashnode Blog data"
          feed_list: "https://polilluminato.hashnode.dev/rss.xml"
```

**Expected behavior**
I expected to see the list of the last 5 blog posts on Hashnode based on my RSS feed but nothing appears.
