### ISSUE TITLE
[Bug]: Url is wrong for github generated pages feed

### ISSUE THREAD

**Issue by jhoelzel** [gautamkrishnar/blog-post-workflow#133]
**Describe the bug**
I use the RSS feed from a github genereated page and it comes without protocol. Therefore the post-bot adds faulty links to my mainpage.

**Expected behavior**
i have an url without a protocoll, or the workflow assumes ssl

**Screenshots**
it can bee seen live here: 
https://github.com/jhoelzel/jhoelzel

the repository of the blog can be found here:
https://github.com/jhoelzel/jhoelzel.github.io

**Workflow Yml Used**
```yml
        - uses: gautamkrishnar/blog-post-workflow@master
          with:
            # Replace this URL with your rss feed URL/s
            feed_list: "https://www.hoelzel.it/feed.xml"
            max_post_count: 10
            template: "- `$date` | [$title]($url)  $newline"
            date_format: yyyy-mm-dd
            tag_post_pre_newline: true
```

**Additional context**
Thank you for this workflow I love it!

**Comment by gautamkrishnar** [comment]
@jhoelzel i recommend you to fix your source code to include the post url in a valid format ie: `https://www.hoelzel.it/argocd/2022/03/23/redeploy-argocd-autopilot-project.html` in `https://www.hoelzel.it/feed.xml`. Since its not a valid url your SEO perfomance may be impacted too.  Search engines like google will throw serrs crawling your website. 

Alternatively you can do the following to fix the issue:
```yaml
    - uses: gautamkrishnar/blog-post-workflow@master
          with:
            # Replace this URL with your rss feed URL/s
            feed_list: "https://www.hoelzel.it/feed.xml"
            max_post_count: 10
            template: "- `$date` | [$title]($url)  $newline"
            date_format: yyyy-mm-dd
            tag_post_pre_newline: true
            item_exec: |
                     post.url = "https://" + post.url 
```
