### ISSUE TITLE
[Feature]: Can I set a tag, and let those blog posts don't show in the readme?

### ISSUE THREAD

**Issue by PttCodingMan** [gautamkrishnar/blog-post-workflow#140]
As title.

Can I set a tag? For example LeetCode.
Let those blog posts don't show in the readme.

Many thanks.

**Comment by gautamkrishnar** [comment]
> Can I set a tag? For example LeetCode.
Can you please elaborate more about what you are looking for. Can you please share a concrete example of it.

If you meant using custom tags, yes the workflow currenly supports it. See `custom_tags` in options section: https://github.com/gautamkrishnar/blog-post-workflow#options

**Comment by PttCodingMan** [comment]
When I set "LeetCode" in custom_tags, my readme only shows the "LeetCode" post.
But I don't want to show the "LeetCode" posts on my readme.

What can I do?

Many thanks.

**Comment by gautamkrishnar** [comment]
```
When I set "LeetCode" in custom_tags, my readme only shows the "LeetCode" post.
```

Sorry i still dont understand what exactly are you trying to acheive here. Please share the code examples if you used any.

**Comment by gautamkrishnar** [comment]
from looking at your readme i guess you are trying to remove "LeetCode" string from the title. 
<img width="652" alt="Screenshot 2022-05-18 at 2 06 20 PM" src="https://user-images.githubusercontent.com/8397274/168995829-18fd7726-0edb-4b52-8a60-1141a5e3db58.png">

You can do it using the following code:
```yaml
on:
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  push:
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in codingman.cc posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          timeout_seconds: 60
          max_attempts: 3
          feed_list: "https://codingman.cc/atom.xml"
          item_exec: |
               title = title.replace("LeetCode ", "");
```

**Comment by PttCodingMan** [comment]
Sorry, English is not my native language. I can't express it well.
Let me explain it another way.

I don't want to see any posts has LeetCode tag on GitHub profile.

**Comment by Bear1110** [comment]
I think the goal is user want to ignore some of the "custom_tag". In order to  prevent posting "custom_tag" of posts  on the github readme profile.

For the usecase of PttCodingMan, because he does not want to show posts related about Leetcode on his profile.

**Comment by gautamkrishnar** [comment]
@PttCodingMan its okay, tnanks for explaining. You can do it like this:
```yaml
on:
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  push:
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in codingman.cc posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          timeout_seconds: 60
          max_attempts: 3
          feed_list: "https://codingman.cc/atom.xml"
          custom_tags: 'tag/category/'
          item_exec: |
                if (customTags.tag.$.term.toLowerCase() === "leetcode") post = null;
```
