### ISSUE TITLE
[Feature]: Do not fail if feed has items without title

### ISSUE THREAD

**Issue by krossovochkin** [gautamkrishnar/blog-post-workflow#142]
Hi

My feed is failing because it has item with empty title: https://github.com/krossovochkin/krossovochkin/actions/runs/2465879885

I don't want to display that item w/o title but it seem to fail parsing overall and workflow doesn't work.

As I have limited control on the feed and that item with no title is actually not a post, I'd like to ask you to support parsing of such items and filtering them out afterwards so that they are not displayed in profile

Thanks!

**Comment by gautamkrishnar** [comment]
@krossovochkin this feature already exists, just use the following:
```yml
name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://krossovochkin.github.io/index.xml"
          disable_item_validation: true
          item_exec: |
                if(!post.title) post = null;
```
