### ISSUE TITLE
HTML tags are not rendered inside the $description [Bug]: 

### ISSUE THREAD

**Issue by Qiamast** [gautamkrishnar/blog-post-workflow#148]
**Describe the bug**
HTML tags are not rendered inside the $description

**Expected behavior**
I used your project to get a podcast feed and works for me so well but when I get the podcast feed $description I see an HTML tag in the description that is not rendered and shows plain text! 
And this is not what I'm looking for

[my project repository](https://github.com/Qiamast/RadioGeek)

**Screenshots**
![BUG](https://user-images.githubusercontent.com/78082316/175127049-a1e601ca-76b7-4e1c-949c-c293ee1ee1cb.png)

**Workflow Yml Used**
```yml
name: Latest RadioGeek (Anchor)
on:
  schedule:
    # Runs “At 00:00 on Friday.”
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  update-readme-with-anchor:
    name: Update this repo's README with the latest RadioGeek podcast feed from Anchor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "RadioGeek-Anchor-feed"
          feed_list: "https://anchor.fm/s/6048890/podcast/rss"
          max_post_count: 1000
          commit_message: "🔥Update with lastest RadioGeek feed"
          committer_username: "🤖RadioGeek-Bot"
          committer_email: "<>"
          template: "$newline #### - [$title]($url) $newline <details> $description </details> $newline <hr /> $newline"

```

**Comment by gautamkrishnar** [comment]
@Qiamast this is not an issue related to this workflow. It is just because of GitHub readme rendering itself. Please report the issue to GitHub.

**Comment by gautamkrishnar** [comment]
@Qiamast you can use `item_exec` to remove the `<p>` tags if you want.

**Comment by Qiamast** [comment]
> @Qiamast you can also use `item_exec` to remove the `<p>` tags if you want from the description.

thank you :) I try this

**Comment by Qiamast** [comment]
i use this code for ignore html tag in details but think not work :/
```yml
item_exec: "post.description = post.description.replace(/<[^>]*>/,'')"
```

**Comment by gautamkrishnar** [comment]
@Qiamast sorry i totally forgot that we have `disable_html_encoding` please use that option. Please use the following:
```yaml
name: Latest RadioGeek (Anchor)
on:
  schedule:
    # Runs “At 00:00 on Friday.”
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  update-readme-with-anchor:
    name: Update this repo's README with latest RadioGeek podcast feed from Anchor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "RadioGeek-Anchor-feed"
          feed_list: "https://anchor.fm/s/6048890/podcast/rss"
          max_post_count: 1000
          commit_message: "🔥Update with lastest RadioGeek feed"
          committer_username: "🤖RadioGeek-Bot"
          committer_email: "<>"
          date_format: 'UTC: yyyy-mm-dd'
          template: "$newline #### - [$title]($url) $newline <details> $description </details> $newline <hr /> $newline"
          disable_html_encoding: true
```
Its working:
![Screenshot 2022-06-23 at 1 59 05 PM](https://user-images.githubusercontent.com/8397274/175253733-39040bc7-cf89-4981-92bf-a2593ac86247.png)

**Comment by Qiamast** [comment]
This is great, I appreciate you🔥✨
i use this regex for ignore HTML tag :)
```yml
post.description.replace(/(<([^>]+)>)/ig
```

**Comment by Qiamast** [comment]
in your screenshot from detail view soo well, but in my pc, I little bad view, don't know way?????

![tprlQMClSYQ-00-26-24](https://user-images.githubusercontent.com/78082316/175274418-ddf38fb8-122c-4831-a7d1-ae29861d6188.png)

**Comment by gautamkrishnar** [comment]
@Qiamast don't use `item_exec` just use the exact yaml i shared. It will work.

```yaml
name: Latest RadioGeek (Anchor)
on:
  schedule:
    # Runs “At 00:00 on Friday.”
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  update-readme-with-anchor:
    name: Update this repo's README with latest RadioGeek podcast feed from Anchor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "RadioGeek-Anchor-feed"
          feed_list: "https://anchor.fm/s/6048890/podcast/rss"
          max_post_count: 1000
          commit_message: "🔥Update with lastest RadioGeek feed"
          committer_username: "🤖RadioGeek-Bot"
          committer_email: "<>"
          date_format: 'UTC: yyyy-mm-dd'
          template: "$newline #### - [$title]($url) $newline <details> $description </details> $newline <hr /> $newline"
          disable_html_encoding: true
```
