### ISSUE TITLE
[Bug]: Error: Feed not recognized as RSS 1 or 2.

### ISSUE THREAD

**Issue by SingularisArt** [gautamkrishnar/blog-post-workflow#155]
**Describe the bug**
For quite some time, when I run the workflow, it just immediately quits and gives me the error: `Error: Feed not recognized as RSS 1 or 2` and I don't know what to do.

**Expected behavior**
I expected the workflow to get all of my posts.

**Workflow Yml Used**
```yml
name: "Latest blog post"
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: "Update this repo's README with latest blog posts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://damrah.netlify.app/index.xml"
```

**Additional context**
My website was made in **Hugo**, a go framework.
Here's a snippet of my **README.md**

```md
### 📕 &nbsp;Latest Blog Posts
<!-- BLOG-POST-LIST:START -->
<!-- BLOG-POST-LIST:END -->
```
