### ISSUE TITLE
[Bug]:  style does not work on Youtube videos

### ISSUE THREAD

**Issue by ghorbani-mohammad** [gautamkrishnar/blog-post-workflow#159]
**Describe the bug**
Hi there, I want to remove borders from the videos item so I give the below attribute to td elements. But it seems that style attribute will be removed after running the action
```css
style="border:none;"
```

**Expected behavior**
I don't want to see borders outside of videos.

**Screenshots**
I want to remove this borders.
![image](https://user-images.githubusercontent.com/12118217/180926043-fa8ee64a-769e-462a-9b0b-f974e8e9bc8a.png)

**Workflow Yml Used**
```yml
name: Latest Youtube videos workflow
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6wsMDXvLDbUi6aw1xhVbNA"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: '<table><tr><td style="border:none;"><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td style="border:none;"><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          committer_email: "michael.ghorb@gmail.com"
          comment_tag_name: "YOUTUBE-POST-LIST"
```
