### ISSUE TITLE
[Feature]: Open Links in New Tab

### ISSUE THREAD

**Issue by YusufcanY** [gautamkrishnar/blog-post-workflow#164]
**Is your feature request related to a problem? Please describe.**
It's not releted to a problem.

**Describe the solution you'd like**
Just add a `target="_blank"` to `<a>` tag

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by gautamkrishnar** [comment]
@YusufcanY you can do that easily using the template option. Eg:
```yaml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
          template: "<li><a href="$url" target="_blank">$title</a></li>"
```

in readme:
```md
# Blog posts
<ul>
<!-- BLOG-POST-LIST:START -->
<!-- BLOG-POST-LIST:END -->
<ul>
```
