### ISSUE TITLE
[Bug]: Error: certificate has expired

### ISSUE THREAD

**Issue by BowenYoung** [gautamkrishnar/blog-post-workflow#172]
**Describe the bug**
Hello, I use hexo to generate my rss feed. And I've tried `atom` and `rss2`. But the actions failed for the same reason`Error: certificate has expired`.

**Expected behavior**
It succeeded before(about two months ago) with the same configuration. So I think it should still work. 
![success](https://kjimg10.360buyimg.com/ott/jfs/t1/216011/1/22051/105860/6346a63dE11ca60c7/85e62a47b9bbc1e9.png)

**Screenshots**
![screenshot](https://kjimg10.360buyimg.com/ott/jfs/t1/82180/11/22545/69417/6346a586Ee802816c/7a2445af12e1a93a.png)
And you can see live: <https://github.com/BowenYoung/BowenYoung/actions>

**Workflow Yml Used**
```yml
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://bowenyoung.cn/atom.xml"
```

**Additional context**
Thanks for help!!!
