### ISSUE TITLE
[Bug]: Not fetching fancy font of medium blog title

### ISSUE THREAD

**Issue by arjun-ms** [gautamkrishnar/blog-post-workflow#178]
**Describe the bug**
From the below-attached screenshot, you can see that I have a blog named "Find Hackathons and Win Them 🏆" and it's written in a fancy font. But the title is not fetched in the RSS properly.

**Expected behavior**
The readme should show the fancy font as it is or convert it into a regular font and then show it.

**Screenshots**
![image](https://user-images.githubusercontent.com/64315213/198863481-9fb664ce-6c91-4fae-8310-255c2a3d4429.png)
---
![bug](https://user-images.githubusercontent.com/64315213/198863768-ba27d3da-5b7b-4cc6-b7df-db63a0a9d12c.png)
---
![image2](https://user-images.githubusercontent.com/64315213/198863791-efc19527-577b-4ef5-a827-f54bd127f891.png)
---
**Workflow Yml Used**
```yml
name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://medium.com/feed/@arjun-ms"
```

**Additional context**
Reference Links
- [Medium blog post](https://medium.com/@arjun-ms/-fb09722e21d6)
- [My GitHub Readme](https://github.com/arjun-ms/arjun-ms)
- [My Medium RSS feed](https://medium.com/feed/@arjun-ms)
