### ISSUE TITLE
[Bug]: Unable to fetch RSS feed | Error with status code: 503

### ISSUE THREAD

**Issue by soumendrak** [gautamkrishnar/blog-post-workflow#179]
**Describe the bug**
```
Run gautamkrishnar/blog-post-workflow@master
  with:
    feed_list: https://blog.soumendrak.com/rss.xml
    gh_token: ***
    readme_path: ./README.md
    max_post_count: 5
    disable_sort: false
    filter_comments: medium,stackoverflow/Comment by $author/,stackexchange/Comment by $author/
    template: default
    date_format: UTC:ddd mmm dd yyyy h:MM TT
    user_agent: rss-parser
    accept_header: application/rss+xml
    commit_message: Updated with the latest blog posts
    committer_username: blog-post-bot
    committer_email: blog-post-bot@example.com
    output_only: false
    enable_keepalive: true
    retry_count: 0
    retry_wait_time: [1](https://github.com/soumendrak/soumendrak/actions/runs/3355743277/jobs/5560245386#step:3:1)
    disable_html_encoding: false
    categories_template: default
    disable_item_validation: false
Error: https://blog.soumendrak.com/rss.xml runner failed, please verify the configuration. Error:
Error: Error: Status code 50[3](https://github.com/soumendrak/soumendrak/actions/runs/3355743277/jobs/5560245386#step:3:3)
```
It was working perfectly till 25 September.

**Expected behavior**
There should not be any errors and blog posts should be updated. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10120538/198882885-be31205e-d525-4018-bfe3-ba23bb55d2dd.png)

**Workflow Yml Used**
```yml
# reference: https://iamdarshshah.hashnode.dev/how-to-add-your-recently-published-articles-to-your-github-profile-readme-using-github-actions
name: Latest blog post workflow
on:
 schedule: # Run workflow automatically
   # This will make it run every hour
   - cron: '0 * * * *' 
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update this repo's README with latest blog posts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: gautamkrishnar/blog-post-workflow@master
       with:
         # Replace this URL with your rss feed URL/s
         feed_list: "https://blog.soumendrak.com/rss.xml"

```

**Additional context**
N/A
