### ISSUE TITLE
[Bug]: Post Count is not Correct - Medium

### ISSUE THREAD

**Issue by muhammedsaidkaya** [gautamkrishnar/blog-post-workflow#181]
**Describe the bug**
The problem is post count is not correct when I dispatch the workflow. 

**Expected behavior**
Post count must be 3.

**Screenshots**
![image](https://user-images.githubusercontent.com/32541088/202854930-a8f8afd6-3a8f-453e-8195-77266dd8d650.png)
![image](https://user-images.githubusercontent.com/32541088/202854942-d7caf404-dceb-4955-9af7-518f065e6004.png)
![image](https://user-images.githubusercontent.com/32541088/202855012-2b9b91e4-82e2-4649-9740-a06a81e9b448.png)

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/@muhammedsaidkaya/feed"
```

**Additional context**
