### ISSUE TITLE
Unknown error: 0 blog posts fetched

### ISSUE THREAD

**Issue by iphysresearch** [gautamkrishnar/blog-post-workflow#186]
The error in Actions reads as below:
```shell
Run gautamkrishnar/blog-post-workflow@v1
Error: https://iphysresearch.github.io/blog/post/index.xml runner failed, please verify the configuration. Error:
0 blog posts fetched
```
I don't know why. Maybe the format in [https://iphysresearch.github.io/blog/post/index.xml](https://iphysresearch.github.io/blog/post/index.xml) is not right?

I also show the workflow as below (also see [here](https://github.com/iphysresearch/iphysresearch/blob/main/.github/workflows/blog-post-workflow.yml))

```yml
name: Latest blog post workflow
on:
  push:
    branches:
      - main
  schedule:
    # workflow runs every hour
    - cron: '0 * * * *'
    #- cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull from posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          #feed_list: 'http://fetchrss.com/rss/5f9c23f4ee36980a6b59c7f25f9c24ef0235fb0ef307f362.xml'
          feed_list: 'https://iphysresearch.github.io/blog/post/index.xml'
          #feed_list: 'https://iphysresearch.github.io/blog/project/index.xml'
          #feed_list: 'https://iphysresearch.github.io/blog/author/herb/index.xml'
          #feed_list: 'https://iphysresearch.github.io/blog/index.xml'
          #feed_list: 'https://offering.solutions/index.xml'
          user_agent: 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
          accept_header: 'text/xml'
          description_max_length: "40"
          tag_post_pre_newline: "true"
          max_post_count: "10"

```

**Comment by gautamkrishnar** [comment]
@iphysresearch it is because one of your blog post item doesn't have a title, you can skip this validation by setting:
```yaml
name: Latest blog post workflow
on:
  push:
    branches:
      - main
  schedule:
    # workflow runs every hour
    - cron: '0 * * * *'
    #- cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull from posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          #feed_list: 'http://fetchrss.com/rss/5f9c23f4ee36980a6b59c7f25f9c24ef0235fb0ef307f362.xml'
          feed_list: 'https://iphysresearch.github.io/blog/post/index.xml'
          #feed_list: 'https://iphysresearch.github.io/blog/project/index.xml'
          #feed_list: 'https://iphysresearch.github.io/blog/author/herb/index.xml'
          #feed_list: 'https://iphysresearch.github.io/blog/index.xml'
          #feed_list: 'https://offering.solutions/index.xml'
          user_agent: 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
          accept_header: 'text/xml'
          description_max_length: "40"
          tag_post_pre_newline: "true"
          max_post_count: "10"
          disable_item_validation: true
```
