### ISSUE TITLE
[New Source]: Latest Podcast Episode from Anchor

### ISSUE THREAD

**Issue by Qiamast** [gautamkrishnar/blog-post-workflow#193]
```yaml

name: Latest RadioGeek (Anchor)
on:
  schedule:
    # Runs “At 00:00 on Friday.”
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  update-readme-with-anchor:
    name: Update this repo's README with latest RadioGeek podcast feed from Anchor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "RadioGeek-Anchor-feed"
          feed_list: "https://anchor.fm/s/6048890/podcast/rss"
          max_post_count: 1000
          commit_message: "🔥Update with lastest RadioGeek feed"
          committer_username: "🤖RadioGeek-Bot"
          committer_email: "<>"
          date_format: 'UTC: yyyy-mm-dd'
          template: "$newline #### - [$title]($url) $newline <details><summary>توضیحات</summary> $description </details> $newline <hr /> $newline"
          # Regex for remove HTML TAG:    /(<([^>]+)>)/ig
          item_exec: "post.description = post.description.replace('','')"
          disable_html_encoding: true
```

Preview :

![01](https://user-images.githubusercontent.com/78082316/215697112-3769ad7b-bfd8-4fba-909e-a906a4c696f2.png)
![02](https://user-images.githubusercontent.com/78082316/215697145-29d29594-6974-4f8e-b017-8a0eddcf67d8.png)

by : [Mahdi Qiamast](https://github.com/Qiamast)

Notice : This repo is private in my account and that's why I haven't mentioned its link
