### ISSUE TITLE
[Bug]: Cannot read response->item->title

### ISSUE THREAD

**Issue by musnows** [gautamkrishnar/blog-post-workflow#201]
**Describe the bug**

```
Update this repo's README with latest blog posts https://blog.musnow.top/atom.xml runner failed, please verify the configuration. Error:
--
Update this repo's README with latest blog posts Cannot read response->item->title
```

**Expected behavior**
It worked well a few days ago, and this problem has arisen in the past two days. 

**Screenshots**

![image](https://user-images.githubusercontent.com/87506951/225863302-077a090c-c551-412e-af81-8cb576e973c5.png)

![image](https://user-images.githubusercontent.com/87506951/225864257-ff563274-50a5-46d4-a0b2-924ccbf0905a.png)

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.musnow.top/atom.xml"
          date_format: yy-mm-dd
```

**Additional context**

I think it may be a connection error. I tried follow url's (they are all the same website), the issue is still there

```bash
https://blog.musnow.top/atom.xml    # cdn
https://blog1.musnow.top/atom.xml  # netlify
https://musnows.github.io/atom.xml  # github pages
```
