### ISSUE TITLE
[Bug]: fatal: unable to access

### ISSUE THREAD

**Issue by scshiv29-dev** [gautamkrishnar/blog-post-workflow#203]
**Describe the bug**
getting this error when the action tries to write in the readme
**Expected behavior**
so the runner gets the posts but is unable to post it on readme
**Screenshots**
![image](https://user-images.githubusercontent.com/68141773/227473383-887ed152-e6ec-4b18-944d-7bf2b7387c34.png)

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://shivamchaudhary.pro/rss/"
```
`
**Additional context**
