### ISSUE TITLE
[Bug]: Fails when there is no <title> in <item>

### ISSUE THREAD

**Issue by nie7321** [gautamkrishnar/blog-post-workflow#205]
**Describe the bug**
When there is no `<title>` in an RSS feed's `<item>`, [the action fails](https://github.com/nie7321/nie7321/actions/runs/4667710149/jobs/8263849935#step:3:30):

```
            title: item.title.trim(),
                              ^

TypeError: Cannot read properties of undefined (reading 'trim')
```

**Expected behavior**
The RSS file in question is from a microblogging site. It's a valid RSS 2.0 file. Per the [RSS 2.0 specification](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt):

>  All elements of an item are optional, however at least one of title or description must be present.

In this feed, `<title>` is absent, but `<description>` is available:

```xml
    <item>
      <guid isPermaLink="true">https://mastodon.yshi.org/@owls/110177333762426246</guid>
      <link>https://mastodon.yshi.org/@owls/110177333762426246</link>
      <pubDate>Tue, 11 Apr 2023 00:24:55 +0000</pubDate>
      <description>&lt;p&gt;!deer&lt;/p&gt;</description>
    </item>
```

If you would like to see the whole feed, it is available at `https://mastodon.yshi.org/@owls.rss`.

**Screenshots**

**Workflow Yml Used**
```yml
name: Dynamic README
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_names: "owlblog,microblog"
          feed_list: "https://godless-internets.org/feed/,http://mastodon.yshi.org/@owls.rss"
```
