### ISSUE TITLE
Action throws error after Update

### ISSUE THREAD

**Issue by kristofzerbe** [gautamkrishnar/blog-post-workflow#210]
**Describe the bug**
With the new version 5 days ago, my action using blog-postworkflow throws the error `Error: TypeError: Cannot convert object to primitive value`.

**Expected behavior**
Run without error

**Workflow Yml Used**
```yml
name: Latest blog post workflow # https://github.com/gautamkrishnar/blog-post-workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 12 * * *' # Runs on 12h hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-latest-posts:
    name: Update this repo's README with latest blog posts from kiko.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://kiko.io/atom.xml"
          max_post_count: 6
          date_format: UTC:dd mmm yyyy
          custom_tags: "thumbImage/media:thumbnail/" #Issue: https://github.com/gautamkrishnar/blog-post-workflow/issues/28
          template: $newline - [$title]($url)   $newline $date   $newline 
```

**Additional context**
My config doesn't changed
