### ISSUE TITLE
Question: Custom WorkFlow, Fetch Blog Post 

### ISSUE THREAD

**Issue by rafay99-epic** [gautamkrishnar/blog-post-workflow#213]
# Question: 
So I have my own blog website called [Future Insight](https://future-insight.blog), and I want to get the latest blog from my website and display it in my GitHub read me file, but it does not seem to be working.

So can you help out?

## My Work Flow:
here is the workflow that I am using
```yml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull Blog Post from Future Insight
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://future-insight.blog"

```

# Screen Shots:
Here are some of the Screen Shots of failed run time
![image](https://user-images.githubusercontent.com/82662797/235764925-51dd4bca-bc35-4d26-ab49-9ae1780fa20c.png)

You can checkout my repo as well by [clicking here](https://github.com/rafay99-epic/rafay99-epic)
