### ISSUE TITLE
[Bug]: The feature blog post work flow is not working for me

### ISSUE THREAD

**Issue by AvinashMahanthi** [gautamkrishnar/blog-post-workflow#23]
**Describe the bug**
A clear and concise description of what the bug is, I had followed the instructions as mentioned by you, but still I am not getting by recent blogs on my readme file.
here is the link to my [repository](https://github.com/AvinashMahanthi/AvinashMahanthi)

**Comment by AvinashMahanthi** [comment]
I had updated all the changes you told me. But still, the workflow is not working. @gautamkrishnar

**Comment by gautamkrishnar** [comment]
@AvinashMahanthi you also messed up the indentation of jobs key: https://github.com/AvinashMahanthi/AvinashMahanthi/actions/runs/220962593, Please fix it, try copy-pasting the below content:
```
name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
        

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@AvinashMahanthi"
```

**Comment by gautamkrishnar** [comment]
Working fine for me: https://github.com/gkr-bot/gkr-bot/runs/1018901935?check_suite_focus=true

**Comment by AvinashMahanthi** [comment]
Could u plz check that now, and kindly say where I had mistaken! and how can you check errors for a particular commit like this https://github.com/AvinashMahanthi/AvinashMahanthi/actions/runs/220962593
could you plz say how to check that also @gautamkrishnar

**Comment by gautamkrishnar** [comment]
@AvinashMahanthi just click on the actions tab in your repo or go to https://github.com/AvinashMahanthi/AvinashMahanthi/actions you can see a list of previous runs.

**Comment by gautamkrishnar** [comment]
@AvinashMahanthi also added a comment on your https://github.com/AvinashMahanthi/AvinashMahanthi/commit/afce774fe117a685b7a2e0cbb7171a0d553299e8 commit for your understanding. The latest code should work or you can use `workflow_dispatch` event if you need to trigger it right now,.

**Comment by AvinashMahanthi** [comment]
could you please say how can we trigger work flow dispatch, I had checked
that on internet but It is explained in the previous version of github, so
please kindly help!

**Comment by gautamkrishnar** [comment]
@AvinashMahanthi Just copy-paste the following contents:
```
name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
        

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@AvinashMahanthi"
```
Commit the change.
Watch this video to know how you can trigger it manually: https://youtu.be/ECuqb5Tv9qI?t=649
