### ISSUE TITLE
[Bug]: The max_post_count parameter doesn't work for my workflow and feed elements

### ISSUE THREAD

**Issue by dassiorleando** [gautamkrishnar/blog-post-workflow#236]
### Describe the bug
I set up a GitHub action using this blog-post workflow, I used 500 as the **max_post_count**, and my feed returns **48 elements** but my README file only has **10 posts** listed.

### Expected behavior
From my understanding of the documentation, the **max_post_count** parameter is there to define the maximum number of items to have listed in my README file, and right now even if I send 48 elements, it always lists 10 blog posts.

### Screenshots
![image](https://github.com/gautamkrishnar/blog-post-workflow/assets/7150752/bef345f6-7e4d-4395-8104-77ac45ac0ec8)

### Workflow Yml Used
```yml
name: All the articles workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with all the articles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull Ni posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 500
          readme_path: './articles/README.md'
          comment_tag_name: "ALL-POSTS-LIST"
          feed_list: "https://numericaideas.com/feed/"
```

### Additional context
Here is the README as output: https://github.com/numerica-ideas/community/blob/master/articles/README.md

### Double check the following
Before opening a bug, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [x] I had gone through the [FAQs](https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues) 
- [x] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)
