### ISSUE TITLE
[Bug]: Substack RSS Feeds returning 403s?

### ISSUE THREAD

**Issue by aashutoshrathi** [gautamkrishnar/blog-post-workflow#240]
### Describe the bug
Hashnode feeds gets fetched fine, but Substack feed is returning 403.

### Expected behavior
Working fine with substack

### Screenshots
<img width="1089" alt="image" src="https://github.com/gautamkrishnar/blog-post-workflow/assets/21199234/20dad4c7-724c-4f3e-9fdf-c7d3cf12d573">

### Workflow Yml Used
```yml
name: Lastest Blogs
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGS"
          committer_username: "automation.aashutosh.dev"
          committer_email: "automation@aashutosh.dev"
          commit_message: "Update with latest blogs"
          feed_list: "https://blog.aashutosh.dev/rss.xml,https://thenibble.substack.com/feed.xml"
          remove_duplicates: true
```

### Additional context
Not sure if this is something we can fix on the action side, but any solutions are welcome. Seems like Substack blocked GitHub action runners, so maybe we need proxy?

### Double check the following
Before opening a bug, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [x] I had gone through the [FAQs](https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues) 
- [x] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)
