### ISSUE TITLE
[New Source]: NAVER

### ISSUE THREAD

**Issue by bnbong** [gautamkrishnar/blog-post-workflow#241]
Source Name: NAVER

Source URL: https://rss.blog.naver.com/blog_id.xml

Comments: 
Hello, thank you so much for providing such wonderful features that I can decorate my Github Profile README even more beautifully.
I wanted to contribute to your project, so I left an issue.
NAVER, what I'm trying to add to Popular Sources section, is most famous portal site in Korea.
NAVER blogs have already supported RSS functions for a long time, and I have used this project to confirm that the blog post workflow function is fully applicable with NAVER blogs.
And rightly so, it has been applied as normal.

Example: replace `blog_id` with your NAVER blog id, e.g. https://rss.blog.naver.com/bnbong.xml
In your blog-post-workflow.yml, write feed_list section e.g.
```YAML
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rss.blog.naver.com/bnbong.xml" # HERE
```
If you want to see an example of a blog post working with README by applying NAVER blog RSS, you can find it in my Github profile link below:
https://github.com/bnbong
