### ISSUE TITLE
[Bug]: WorkFlow failed with 404 error, But I'm sure the website does work

### ISSUE THREAD

**Issue by forrany** [gautamkrishnar/blog-post-workflow#244]
### Describe the bug
WorkFlow failed with error message:

```bash
Error: https://vincentko.top/rss.xml runner failed, please verify the configuration. Error:
Error: Looks like your website returned 404, There is nothing blog post workflow can do to fix it. Please check your website's RSS feed generation source code. Also double check
            the URL.
```

But I'm so sure that my website works well and I can open it throw Browser: https://vincentko.top/rss.xml 

### Expected behavior
WorkFlow should be successed

### Screenshots
<img width="1696" alt="image" src="https://github.com/gautamkrishnar/blog-post-workflow/assets/29779326/dd5ee07d-f0fa-4d7d-bb57-d4cdaaff41df">

### Workflow Yml Used
```yml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://vincentko.top/rss.xml"
```

### Double check the following
Before opening a bug, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [x] I had gone through the [FAQs](https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues)
- [x] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)
