### ISSUE TITLE
JSON output is not working

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/blog-post-workflow#262]
> I'm returning to this topic.
> Every time I try to output it to `blog_post_workflow_output.json`, I still get the same error.
> And I created the `tmp` folder everywhere, in the root, in `.github`, in `.github/workflows` - everything is useless. I know that this will not affect the result, but still, trying is not torture.
> And what do I think about this... The `tmp` folder simply does not exist, and we are trying to write a file to it. > Accordingly, an error. [L13931](https://github.com/gautamkrishnar/blog-post-workflow/blob/master/dist/blog-post-workflow.js#L13931)
> At least that's how it is for me.
> Maybe add the creation of this folder?
> Like this:
```javascript
fs.mkdirSync(path.join("/", "tmp"), {recursive: true});
```

_Originally posted by @ProjectSoft-STUDIONIONS in https://github.com/gautamkrishnar/blog-post-workflow/issues/110#issuecomment-2242680492_

**Comment by gautamkrishnar** [comment]
@ProjectSoft-STUDIONIONS i am not seeing any issues with JSON output. example: https://github.com/gkr-bot/test-001/actions/runs/10537446330/job/29198842837

Yaml: 
```yaml
name: All the articles workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with all the articles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Keepalive
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          output_only: true
          feed_list: "https://dev.to/feed/gautamkrishnar"
      - run: cat /tmp/blog_post_workflow_output.json
        
```
