### ISSUE TITLE
[Bug]: Successfully pulled, but the number of articles is 0

### ISSUE THREAD

**Issue by yuanj82** [gautamkrishnar/blog-post-workflow#268]
### Describe the bug
Successfully pulled, but the number of articles is 0

### Expected behavior
```yaml
name: Latest blog posts workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 50
          retry_count: 5
          readme_path: "./content/_index.md"
          date_format: "mmm d, yyyy"
          filter_dates: "currentMonth"
          comment_tag_name: "Posts"
          template: "$newline- [ $title ]($url) | $date"
          feed_list: >
            https://tech.meituan.com/feed/,
            https://k1r.in/rss.xml,
            https://www.eaimty.com/rss.xml,
```

### Workflow Yml Used
```yml
Insert the workflow's yml file you used
```

### Additional context
The actions log is as follows
```yaml
Previous try for https://darmau.co/zh/article/rss.xml failed, retrying: 1
https://tech.meituan.com/feed/ runner succeeded. Post count: 0
https://k1r.in/rss.xml runner succeeded. Post count: 0
https://www.eaimty.com/rss.xml runner succeeded. Post count: 0
https://thiscute.world/index.xml runner succeeded. Post count: 0
https://raw.githubusercontent.com/yihong0618/gitblog/master/feed.xml runner succeeded. Post count: 0
https://www.archlinuxcn.org/feed/ runner succeeded. Post count: 0
https://openbiox.github.io/weekly/feed_rss_created.xml runner succeeded. Post count: 0
https://limboy.me/index.xml runner succeeded. Post count: 0
https://blog.ursb.me/feed.xml runner succeeded. Post count: 0
https://lutaonan.com/rss.xml runner succeeded. Post count: 0
https://tw93.fun/feed.xml runner succeeded. Post count: 0
https://1q43.blog/feed runner succeeded. Post count: 0
https://www.pseudoyu.com/zh/index.xml runner succeeded. Post count: 0
https://weekly.tw93.fun/rss.xml runner succeeded. Post count: 0
https://diygod.cc/feed runner succeeded. Post count: 0
https://yufree.cn/cn/index.xml runner succeeded. Post count: 0
https://www.owenyoung.com/atom.xml runner succeeded. Post count: 0
https://mednoter.com/feed.xml runner succeeded. Post count: 0
https://geekplux.com/feed.xml runner succeeded. Post count: 0
https://frostming.com/feed.xml runner succeeded. Post count: 0
https://wangyurui.com/feed.xml runner succeeded. Post count: 0
```

### Double check the following
Before opening a bug, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [ ] I had gone through the [FAQs](https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues) 
- [ ] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)
