### ISSUE TITLE
[Bug]: Substack Feed not shown

### ISSUE THREAD

**Issue by nlchitnis** [gautamkrishnar/blog-post-workflow#270]
### Describe the bug

The Workflow is not Showing my latest substack Blog Posts

### Expected behavior

Shows my latest Substack Posts
### Screenshots

![image](https://github.com/user-attachments/assets/18938f4a-cb9a-4cb8-b4e8-125e54d4fd54)

### Workflow Yml Used
```yml
name: Latest blog post workflow
on:
  schedule: 
    - cron: '0 * * * *' 
  workflow_dispatch: 
permissions:
  contents: write 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/nlchitnis, https://nlchitnis.substack.com/feed/"
```

### Double check the following
Before opening a bug, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [ ] I had gone through the [FAQs](https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues) 
- [ ] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)
