### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kangyans** [gautamkrishnar/blog-post-workflow#276]
### Describe the bug
display error: [Accelerated 3D multi-channel <mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML"> ](https://pubmed.ncbi.nlm.nih.gov/38934380/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1F7_W1KYjb2VxxVueveRzyg-swq60S9vYJjSvPBqjUiyMRSs4r&fc=20241220225417&ff=20241221161140&v=2.18.0.post9+e462414)mml:mrowmml:msubsupmml:miB</mml:mi> mml:mn1</mml:mn> mml:mo+</mml:mo></mml:msubsup> </mml:mrow> </mml:math> mapping at 7 T for the brain and heart

### Expected behavior
[Accelerated 3D multi-channel B<sup>+</sup><sub>1</sub> mapping at 7 T for the brain and heart](https://pubmed.ncbi.nlm.nih.gov/38934380/)

### Workflow Yml Used
```
name: Latest blog post workflow

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - uses: actions/checkout@v4
          - uses: gautamkrishnar/blog-post-workflow@v1
            with:
              feed_list: "https://pubmed.ncbi.nlm.nih.gov/rss/search/1Hs5ZC7s01Yj387-KZeDWJE6P5URKOk2xA-j9spxiQKJu7dQGr/?limit=15&utm_campaign=pubmed-2&fc=20241220165528"
              max_post_count: 10
              disable_html_encoding: true
              comment_tag_name: SPIRAL


          - uses: actions/checkout@v4
          - uses: gautamkrishnar/blog-post-workflow@v1
            with:
              feed_list: "https://pubmed.ncbi.nlm.nih.gov/rss/search/1F7_W1KYjb2VxxVueveRzyg-swq60S9vYJjSvPBqjUiyMRSs4r/?limit=15&utm_campaign=pubmed-2&fc=20241220225417"
              max_post_count: 10
              disable_html_encoding: true
              comment_tag_name: LOWRANK
```

### Additional context
None

### Double check the following
Before opening a bug, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [x] I had gone through the [FAQs](https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues) 
- [x] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)
