### ISSUE TITLE
[Bug]: Vercel Security Checkpoint for Hashnode makes the CI return 429

### ISSUE THREAD

**Issue by fbuireu** [gautamkrishnar/blog-post-workflow#277]
### Describe the bug
Looks like Hashnode is hosted in Vercel and behind the RSS URL there's a challenge that prevents the action to crawl the RSS feed.

![Image](https://github.com/user-attachments/assets/a71ebba7-4a7b-4659-bb02-3e3f424c45b5)

This makes the action return a 429 apparently:

![Image](https://github.com/user-attachments/assets/c0ba6f47-a895-456a-b59b-fdb734a094f0)

Source: https://github.com/fbuireu/fbuireu/actions/runs/13939772964/job/39014298323

### Expected behavior
I expect the crawler to fetch Hashnode articles behind the security challenge without returning errors

### Screenshots
Already attached before 😄 

### Workflow Yml Used
```yml
name: Hashnode Latest Articles
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Update ${{ matrix.readme }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        readme: [README.md, README.ca.md, README.es.md, README.it.md]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Hashnode articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: ${{ matrix.readme }}
          comment_tag_name: HASHNODE-LATEST-ARTICLES
          max_post_count: 5
          user_agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0'
          accept_header: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8'
          retry_count: 1
          feed_list: ${{ vars.HASHNODE_RSS }}
          commit_message: 'docs: update ${{ matrix.readme }} with latest Hashnode articles'
```

Also tried without the `accept_header`, `retry_count` and `user_agent` options.

### Double check the following
Before opening a bug, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [x] I had gone through the [FAQs](https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues) 
- [x] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)
