### ISSUE TITLE
[Bug]: Manual run of action triggers "UnhandledPromiseRejectionWarning: Error: Invalid status code: 128"

### ISSUE THREAD

**Issue by khromov** [gautamkrishnar/blog-post-workflow#40]
**Describe the bug**
As per title. The workflow succeeds, but the error is printed in the logs.

**Expected behavior**
Manual completes without errors.

**Log**

```
Run gautamkrishnar/blog-post-workflow@1.3.9
https://khromov.se/feed/ runner succeeded. Post count: 5
Writing to ./README.md
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
Error on: git pull
(node:2452) UnhandledPromiseRejectionWarning: Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/gautamkrishnar/blog-post-workflow/1.3.9/dist/blog-post-workflow.js:116:946)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:2452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[main 9c2adf2] Updated with the latest blog posts
 1 file changed, 3 insertions(+)
To https://github.com/khromov/khromov.git
   85fbe2c..9c2adf2  main -> main
Readme updated successfully in the upstream repository
```

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
  schedule:
    - cron: '0 */4 * * *' 
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.3.9
        with:
          feed_list: "https://khromov.se/feed/"
          max_post_count: 3
```

**Additional context**
