### ISSUE TITLE
[Feature]: Retrieve the "Description" or Custom field for each feed

### ISSUE THREAD

**Issue by Dovives** [gautamkrishnar/blog-post-workflow#44]
Hi, 

First thanks for creating this GitHub Action. It's really helpful !

**Retrieve a field for each post**
Is-it possible to retrieve a field like "Description" for each feed ?

**Additional context**
We would like to generate a newsletter based on multiple feeds. It would interesting if we could grab the "Description" field for each post to bring more info about the post.

**Comment by gautamkrishnar** [comment]
@Dovives thanks a lot for the suggestion just added `$description` that will let you use the description in your `template` parameter. You can also use the existing `custom_tags` parameter if you want to use some custom tags as a template variable.

**Comment by gautamkrishnar** [comment]
This is released on https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.4.1

Example usage:
```
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
          template: "- [$title]($url): $description $newline"
          description_max_length: "40"
          tag_post_pre_newline: "true"
```

@Dovives
