### ISSUE TITLE
[Bug]: Feed can't be read from github.io repo rss

### ISSUE THREAD

**Issue by krossovochkin** [gautamkrishnar/blog-post-workflow#45]
**Describe the bug**
Set up workflow as in your repo (with the only difference that link to feed changed)

**Expected behavior**
Feed is parsed and shown on Readme successfully

**Workflow Yml Used**
```yml  
name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https:/krossovochkin.github.io/index.xml"
```

Error says:
```
Error: https:/krossovochkin.github.io/index.xml runner failed, please verify the configuration. Error:
Error: Error: connect ECONNREFUSED 127.0.0.1:443
```
https://github.com/krossovochkin/krossovochkin/runs/1442964262?check_suite_focus=true

Thank you
