### ISSUE TITLE
[Bug]: Posts are all appearing on one line

### ISSUE THREAD

**Issue by nathaneastwood** [gautamkrishnar/blog-post-workflow#46]
Blog posts are being placed on the same line and not as a bulleted list

You can see here: https://github.com/nathaneastwood/nathaneastwood#-latest-blog-posts

**Comment by gautamkrishnar** [comment]
Hi @nathaneastwood please use:

```
name: Latest blog post workflow
on:
  schedule:
    # Runs at 00:05 every Sunday
    - cron: '5 0 * * Sun'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://nathaneastwood.github.io/index.xml"
```

If you just need the bullet list
