### ISSUE TITLE
[Bug]: Shows wrong stats

### ISSUE THREAD

**Issue by programmer-frog** [gautamkrishnar/blog-post-workflow#47]
**Describe the bug**

I added this workflow to my profile README but for some reason it doesn't show my morning commits to another repo and shows closed issues to my README repo (I closed them yesterday)

**Expected behavior**

I expected that it will show my commits.

**Screenshots**

Look at my profile README [here](https://github.com/programmer-frog/programmer-frog)

**Workflow Yml Used**
```yml
name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
