### ISSUE TITLE
[Feature]: Set the list generated as an output variable so that other actions can consume it

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/blog-post-workflow#51]
the list generated as an output variable so that other actions can consume it and can do stuff with the data. 

Add a flag to set this. Prevent commit to readme if this flag is present.

**Comment by gautamkrishnar** [comment]
https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.4.4 released this one

**Comment by gautamkrishnar** [comment]
The output format will be as follows:

#### Workflow yaml
```yaml
name: Latest blog post workflow
on:
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        id: blog-post-workflow
        with:
          feed_list: "https://www.feedforall.com/sample.xml"
          max_post_count: 2
          output_only: true
      - run: echo  ${{ steps.blog-post-workflow.outputs.results }}
```

#### Results output variable
```json
[
   {
      "title":"RSS Solutions for Restaurants",
      "url":"http://www.feedforall.com/restaurant.htm",
      "description":"<b>FeedForAll </b>helps Restaurant's communicate with customers. Let your customers know the latest specials or events.<br>\r\n<br>\r\nRSS feed uses include:<br>\r\n<i><font color=\"#FF0000\">Daily Specials <br>\r\nEntertainment <br>\r\nCalendar of Events </i></font>",
      "date":"2004-10-19T15:09:11.000Z"
   },
   {
      "title":"RSS Solutions for Schools and Colleges",
      "url":"http://www.feedforall.com/schools.htm",
      "description":"FeedForAll helps Educational Institutions communicate with students about school wide activities, events, and schedules.<br>\r\n<br>\r\nRSS feed uses include:<br>\r\n<i><font color=\"#0000FF\">Homework Assignments <br>\r\nSchool Cancellations <br>\r\nCalendar of Events <br>\r\nSports Scores <br>\r\nClubs/Organization Meetings <br>\r\nLunches Menus </i></font>",
      "date":"2004-10-19T15:09:09.000Z"
   }
]
```

You can use tools like [jq](https://stedolan.github.io/jq/) to read value from the variable. Explaining how to do that is beyond the scope of this project.
