### ISSUE TITLE
[Bug]: Action workflow does not pull latest blogs posts from medium

### ISSUE THREAD

**Issue by lakshyajit165** [gautamkrishnar/blog-post-workflow#52]
**Describe the bug**
I have setup a cron expression to pull the latest blog posts from medium every hour, but it doesn't do so

**Workflow Yml Used**
```yml

name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@lakshyajit165"

```
> Any help would be appreciated
