### ISSUE TITLE
[Bug]: Error: Cannot find the comment tag on the readme:

### ISSUE THREAD

**Issue by rupeshtiwari** [gautamkrishnar/blog-post-workflow#54]
**Describe the bug**
It is keep saying `Error: Cannot find the comment tag on the readme:`

**Expected behavior**
Should post successfully. 

**Screenshots**
![image](https://user-images.githubusercontent.com/330383/106394273-bf0feb80-63c9-11eb-8a75-020110ae1da5.png)
I have the section in my github readme
![image](https://user-images.githubusercontent.com/330383/106394286-d51dac00-63c9-11eb-8294-3e57bc4e4413.png)
https://github.com/rupeshtiwari

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
    schedule: # Run workflow automatically
      # This will make it run every hour
      - cron: '0 * * * *' 
     # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
    workflow_dispatch: 
jobs:
    update-readme-with-blog:
      name: Update this repo's README with latest blog posts
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: gautamkrishnar/blog-post-workflow@master
          with:
            committer_username: rupeshtiwari
            readme_path: ./README.md
            committer_email: fullstackmaster1@gmail.com
            # Replace this URL with your rss feed URL/s
            feed_list: "https://rupeshtiwari.github.io/feed.xml"
            gh_token: ${{ secrets.GH_TOKEN }}
```

**Additional context**
