### ISSUE TITLE
[Bug]: Error: {"code":1,"outputData":""}

### ISSUE THREAD

**Issue by nil0x42** [gautamkrishnar/blog-post-workflow#60]
**Describe the bug**
Since yesterday (2021-03-31 20:00), my blog-post-workflow action fails every hour, with this weird error:
`Error: {"code":1,"outputData":""}`

**Expected behavior**
The job should just succeed, even if there is nothing new to do

**Screenshots**
![Screenshot_2021-04-01_05-52-19](https://user-images.githubusercontent.com/3504393/113249795-ddea0b80-92ae-11eb-815c-aef2d3cf1e3f.png)

**Workflow Yml Used**
```yml
name: Latest Tweets workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # created from twitter search string:
          #   from:nil0x42 min_faves:5 min_retweets:2 -filter:retweets -filter:replies -filter:quote
          feed_list: "https://rss.app/feeds/x4n09N54uqkYSpaC.xml"
          comment_tag_name: LATEST-TWEETS
          item_exec: "post.title = post.title.replace(/(?:\\r\\n|\\r|\\n)/g,' ')"
          title_max_length: 80
          date_format: "mmm dd HH:MM"
          template: "<li>$date <a href='$url'>$title</a></li>$newline"
          tag_post_pre_newline: true
          commit_message: "blog-post-workflow/latest-tweets: update"
          committer_username: latest-tweets
          committer_email: latest-tweets@notamail.co
```

**Additional context**
I've been using this exact workflow for many months and never got any error. And i didn't change anything in the code. But i couldn't figure out how this error started happening
