### ISSUE TITLE
[Bug]: runner failed, please verify the configuration. Error 404

### ISSUE THREAD

**Issue by cybercoder-naj** [gautamkrishnar/blog-post-workflow#65]
**Describe the bug**
I have a workflow that draws from Youtube. For many months, I have used it and it worked perfectly but now it seems to fail.
When I enter the link `https://www.youtube.com/feeds/videos.xml?channel_id=XXXX` in my browser, I get all my data.

**Expected behavior**
I expect the workflow to get the required contents and updated my README.md accordingly.

**Screenshots**
![image](https://user-images.githubusercontent.com/48282810/118221812-f9465a00-b49b-11eb-90f9-d472f3537143.png)

**Workflow Yml Used**
```yml
name: YouTube Videos
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=XXX"
```

**Note:** The link has been double tested. There is no problem there.

**Comment by gautamkrishnar** [comment]
@cybercoder-naj from the action run i can see that the stattus code is 404. It might be a problem in the google's side. 
https://github.com/cybercoder-naj/cybercoder-naj/runs/2581142400?check_suite_focus=true
<img width="1026" alt="Screenshot 2021-05-14 at 12 02 07 PM" src="https://user-images.githubusercontent.com/8397274/118231104-3dd9f180-b4ac-11eb-801f-41ce3c65c6b5.png">

When i opened the url https://www.youtube.com/feeds/videos.xml?channel_id=UCPoU-LKr3XG0IujgCFFt4_A for the first time in my browsser it gave me a 404. When i reloaded the page it showed the feed.

<img width="1552" alt="Screenshot 2021-05-14 at 12 14 47 PM" src="https://user-images.githubusercontent.com/8397274/118232330-010efa00-b4ae-11eb-8dd3-6bdfd760dda6.png">

You can report the same to google.

**Comment by gautamkrishnar** [comment]
@cybercoder-naj  i also tried hitting it a couple of times via CURL, this was the status:
<img width="1552" alt="Screenshot 2021-05-14 at 12 22 22 PM" src="https://user-images.githubusercontent.com/8397274/118233185-32d49080-b4af-11eb-93a7-557a4c575cb2.png">

As you can see there are a lots of 404 and 500 coming from the google's end.

**Comment by gautamkrishnar** [comment]
@cybercoder-naj looks like google fixed it. Its working fine right now. Please try re enabling the workflow.

I had released a new release with the retry feature so that the workflow will rety muliple times if the first try fials: https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.5.6

```yml
name: YouTube Videos
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCPoU-LKr3XG0IujgCFFt4_A"
          retry_count: 10
```
