### ISSUE TITLE
[Bug]: Error Code 128

### ISSUE THREAD

**Issue by Gr8z** [gautamkrishnar/blog-post-workflow#67]
I am getting the following error when I try to run this action with my RSS feed:

```json
{"code":128,"outputData":""}
```

action.yml
```yml
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dohad.dev/feed.xml"
```
