### ISSUE TITLE
[Bug]: Attribute without value error

### ISSUE THREAD

**Issue by aakashmeesho** [gautamkrishnar/blog-post-workflow#71]
**Describe the bug**
Getting "Attribute without value" error on running the workflow.

**Screenshots**
![image](https://user-images.githubusercontent.com/74188631/124243922-08f92b00-db3c-11eb-9b5e-0233df0fe5ac.png)

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/@akashthakur_15975"
```
