### ISSUE TITLE
[Bug]: Attribute without value error

### ISSUE THREAD

**Issue by ATakaSKY** [gautamkrishnar/blog-post-workflow#72]
**Describe the bug**
Getting "Attribute without value" error on running the workflow.

**Screenshots**
<img width="810" alt="image" src="https://user-images.githubusercontent.com/17201629/124244273-668d7780-db3c-11eb-9f6a-ec7ca59afcb7.png">

**Workflow Yml Used**
```yml
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/@akashthakur_15975"
```
