### ISSUE TITLE
[Bug]: Error: Error: ENOENT: no such file or directory, open './README.md'

### ISSUE THREAD

**Issue by sprakash57** [gautamkrishnar/blog-post-workflow#73]
**Describe the bug**
blog-post-workflow is failing every time with the error message `Error: Error: ENOENT: no such file or directory, open './README.md'`

**Expected behavior**
- I have followed every step mentioned in the workflow readme. 
- I have 6 posts in my dev.to account.
- I have added `BLOG-POST-LIST` start and end tag as described in my README file.

Still, the workflow is failing with the above error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/38065786/124485333-13305900-ddca-11eb-99eb-94175b0746cd.png)

![image](https://user-images.githubusercontent.com/38065786/124485507-41ae3400-ddca-11eb-92b9-f6420059afcd.png)

**Workflow Yml Used**
```
name: Recent blog posts
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/sprakash57"
```
** Additional context
Github repo --> https://github.com/sprakash57/sprakash57
P.S - If you happen to visit the repo, the blog list over there is static, since workflow was not working.

**Comment by gautamkrishnar** [comment]
@sprakash57 Its because you renamed the README use the following code:
```yaml
name: Recent Blog Posts
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: "README.MD"
          feed_list: "https://dev.to/feed/sprakash57"
```
You can also merge this PR: https://github.com/sprakash57/sprakash57/pull/1/files
