### ISSUE TITLE
[Feature]: Remove Medium Preview Image from Description

### ISSUE THREAD

**Issue by nicko170** [gautamkrishnar/blog-post-workflow#74]
Hey @gautamkrishnar! 

Firstly, this is amazing, so thank you.

I'd like to ask about getting an option to strip the images from the description generated by Medium. Just a bit too big to be in here I think :-)

Example:  https://github.com/nicko170/nicko170/blob/main/README.md

Thanks again!

**Comment by gautamkrishnar** [comment]
Hi @nicko170 You can do this via `item_exec`:
```yaml
name: Latest blog post workflow
on:
    schedule:
        - cron: '0 * * * *'
    push:
      branches:
        - main

jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                max_post_count: "5"
                feed_list: "https://medium.com/feed/@nicko170"
                template: "- [$title]($url): $description $newline"
                date_format: "UTC:ddd yyyy-mm-dd h:MM:ss TT Z"
                filter_comments: "medium"
                tag_post_pre_newline: "true"
                item_exec: |
                     post.description = post.description.replace(/<\/?[^>]+(>|$)/g, ""); 
```
