### ISSUE TITLE
SSL verify error

### ISSUE THREAD

**Issue by linlih** [gautamkrishnar/blog-post-workflow#9]
Can I close the SSL verify

**Comment by gautamkrishnar** [comment]
Hi, @linlih thanks for reporting this. this need not have to be fixed. It should be done on your server, Please add an FQDN (Fully qualified domain name) to your server https://49.232.199.67/ or use `http://49.232.199.67/feed/` to avoid this error.

**Comment by gautamkrishnar** [comment]
@linlih you can also do something like this to fix it:

```yml
name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
         env:
                NODE_TLS_REJECT_UNAUTHORIZED: "0"
         with:
                max_post_count: "4"
          feed_list: "https://49.232.199.67/feed/"
```
